// @generated by protoc-gen-connect-es v1.1.4 with parameter "target=js"
// @generated from file cc/cc.proto (package cc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Chat, CountChatsRequest, CountChatsResponse, Defaults, Empty, Event, FetchDefaultsRequest, GetMembersRequest, ListChatsRequest, ListChatsResponse, Merge, Message, Messages, MessagesListRequest, PollsRequest, SetBotStateRequest, StreamRequest, User, Users, VoteRequest } from "./cc_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service cc.ChatsAPI
 */
export const ChatsAPI = {
  typeName: "cc.ChatsAPI",
  methods: {
    /**
     * @generated from rpc cc.ChatsAPI.Create
     */
    create: {
      name: "Create",
      I: Chat,
      O: Chat,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.ChatsAPI.Update
     */
    update: {
      name: "Update",
      I: Chat,
      O: Chat,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.ChatsAPI.Get
     */
    get: {
      name: "Get",
      I: Chat,
      O: Chat,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.ChatsAPI.List
     */
    list: {
      name: "List",
      I: ListChatsRequest,
      O: ListChatsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.ChatsAPI.Count
     */
    count: {
      name: "Count",
      I: CountChatsRequest,
      O: CountChatsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.ChatsAPI.Delete
     */
    delete: {
      name: "Delete",
      I: Chat,
      O: Chat,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.ChatsAPI.SetBotState
     */
    setBotState: {
      name: "SetBotState",
      I: SetBotStateRequest,
      O: Chat,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.ChatsAPI.GetBotState
     */
    getBotState: {
      name: "GetBotState",
      I: Chat,
      O: Chat,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.ChatsAPI.ChangeDepartment
     */
    changeDepartment: {
      name: "ChangeDepartment",
      I: Chat,
      O: Chat,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.ChatsAPI.ChangeGateway
     */
    changeGateway: {
      name: "ChangeGateway",
      I: Chat,
      O: Chat,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.ChatsAPI.ChangeStatus
     */
    changeStatus: {
      name: "ChangeStatus",
      I: Chat,
      O: Chat,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.ChatsAPI.MergeChats
     */
    mergeChats: {
      name: "MergeChats",
      I: Merge,
      O: Chat,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.ChatsAPI.SyncChats
     */
    syncChats: {
      name: "SyncChats",
      I: Empty,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
};

/**
 * @generated from service cc.MessagesAPI
 */
export const MessagesAPI = {
  typeName: "cc.MessagesAPI",
  methods: {
    /**
     * @generated from rpc cc.MessagesAPI.Get
     */
    get: {
      name: "Get",
      I: Chat,
      O: Messages,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.MessagesAPI.Send
     */
    send: {
      name: "Send",
      I: Message,
      O: Message,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.MessagesAPI.Update
     */
    update: {
      name: "Update",
      I: Message,
      O: Message,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.MessagesAPI.Delete
     */
    delete: {
      name: "Delete",
      I: Message,
      O: Message,
      kind: MethodKind.Unary,
    },
    /**
     * Vote answers the poll on a message. Anyone with access to the chat may
     * answer, once — voting again replaces the previous answer.
     *
     * @generated from rpc cc.MessagesAPI.Vote
     */
    vote: {
      name: "Vote",
      I: VoteRequest,
      O: Message,
      kind: MethodKind.Unary,
    },
    /**
     * Polls returns the given messages, for reading the answers off their polls.
     *
     * Get would do as well if it were not for its side effects: it marks every
     * message read for the caller and publishes CHAT_READ, which is right for a
     * person opening a chat and wrong for a service collecting answers in the
     * background — it would quietly clear the operators' unread counters. This
     * one reads and nothing else. Access is checked per message, so it returns
     * only what the caller could have opened anyway.
     *
     * @generated from rpc cc.MessagesAPI.Polls
     */
    polls: {
      name: "Polls",
      I: PollsRequest,
      O: Messages,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.MessagesAPI.List
     */
    list: {
      name: "List",
      I: MessagesListRequest,
      O: Messages,
      kind: MethodKind.Unary,
    },
  }
};

/**
 * @generated from service cc.UsersAPI
 */
export const UsersAPI = {
  typeName: "cc.UsersAPI",
  methods: {
    /**
     * @generated from rpc cc.UsersAPI.Me
     */
    me: {
      name: "Me",
      I: Empty,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.UsersAPI.FetchDefaults
     */
    fetchDefaults: {
      name: "FetchDefaults",
      I: FetchDefaultsRequest,
      O: Defaults,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.UsersAPI.GetConfig
     */
    getConfig: {
      name: "GetConfig",
      I: Empty,
      O: Defaults,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.UsersAPI.SetConfig
     */
    setConfig: {
      name: "SetConfig",
      I: Defaults,
      O: Defaults,
      kind: MethodKind.Unary,
    },
    /**
     * Resolves given Users data by their UUIDs
     * And returns all accessible Users for Requestor
     *
     * @generated from rpc cc.UsersAPI.Resolve
     */
    resolve: {
      name: "Resolve",
      I: Users,
      O: Users,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cc.UsersAPI.GetMembers
     */
    getMembers: {
      name: "GetMembers",
      I: GetMembersRequest,
      O: Users,
      kind: MethodKind.Unary,
    },
  }
};

/**
 * @generated from service cc.StreamService
 */
export const StreamService = {
  typeName: "cc.StreamService",
  methods: {
    /**
     * @generated from rpc cc.StreamService.Stream
     */
    stream: {
      name: "Stream",
      I: StreamRequest,
      O: Event,
      kind: MethodKind.ServerStreaming,
    },
  }
};

