// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file cc/cc.proto (package cc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum cc.Role
 */
export const Role = proto3.makeEnum(
  "cc.Role",
  [
    {no: 0, name: "NOACCESS"},
    {no: 1, name: "USER"},
    {no: 2, name: "OWNER"},
    {no: 3, name: "ADMIN"},
  ],
);

/**
 * @generated from enum cc.Kind
 */
export const Kind = proto3.makeEnum(
  "cc.Kind",
  [
    {no: 0, name: "DEFAULT"},
    {no: 1, name: "ADMIN_ONLY"},
  ],
);

/**
 * @generated from enum cc.EventType
 */
export const EventType = proto3.makeEnum(
  "cc.EventType",
  [
    {no: 0, name: "PING"},
    {no: 1, name: "CHAT_CREATED"},
    {no: 2, name: "CHAT_UPDATED"},
    {no: 3, name: "CHAT_DELETED"},
    {no: 4, name: "MESSAGE_SENT"},
    {no: 5, name: "MESSAGE_UPDATED"},
    {no: 6, name: "MESSAGE_DELETED"},
  ],
);

/**
 * @generated from message cc.Empty
 */
export const Empty = proto3.makeMessageType(
  "cc.Empty",
  [],
);

/**
 * @generated from message cc.ChatMeta
 */
export const ChatMeta = proto3.makeMessageType(
  "cc.ChatMeta",
  () => [
    { no: 1, name: "unread", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "last_message", kind: "message", T: Message },
  ],
);

/**
 * @generated from message cc.Chat
 */
export const Chat = proto3.makeMessageType(
  "cc.Chat",
  () => [
    { no: 1, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "users", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "admins", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "owner", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "gateways", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 6, name: "role", kind: "enum", T: proto3.getEnumType(Role) },
    { no: 7, name: "topic", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 8, name: "meta", kind: "message", T: ChatMeta, opt: true },
    { no: 9, name: "created", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message cc.Chats
 */
export const Chats = proto3.makeMessageType(
  "cc.Chats",
  () => [
    { no: 1, name: "chats", kind: "message", T: Chat, repeated: true },
  ],
);

/**
 * @generated from message cc.Attachment
 */
export const Attachment = proto3.makeMessageType(
  "cc.Attachment",
  () => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message cc.Message
 */
export const Message = proto3.makeMessageType(
  "cc.Message",
  () => [
    { no: 1, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "kind", kind: "enum", T: proto3.getEnumType(Kind) },
    { no: 3, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "attachments", kind: "message", T: Attachment, repeated: true },
    { no: 6, name: "gateways", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 7, name: "chat", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 8, name: "sent", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "edited", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "under_review", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 11, name: "readers", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message cc.Messages
 */
export const Messages = proto3.makeMessageType(
  "cc.Messages",
  () => [
    { no: 1, name: "messages", kind: "message", T: Message, repeated: true },
  ],
);

/**
 * @generated from message cc.User
 */
export const User = proto3.makeMessageType(
  "cc.User",
  () => [
    { no: 1, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message cc.Defaults
 */
export const Defaults = proto3.makeMessageType(
  "cc.Defaults",
  () => [
    { no: 1, name: "gateways", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "admins", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message cc.Users
 */
export const Users = proto3.makeMessageType(
  "cc.Users",
  () => [
    { no: 1, name: "users", kind: "message", T: User, repeated: true },
  ],
);

/**
 * @generated from message cc.Event
 */
export const Event = proto3.makeMessageType(
  "cc.Event",
  () => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(EventType) },
    { no: 2, name: "chat", kind: "message", T: Chat, oneof: "item" },
    { no: 3, name: "msg", kind: "message", T: Message, oneof: "item" },
  ],
);

